### ISSUE TITLE
Cannot open context menu

### ISSUE THREAD

**Issue by TheoryOfNekomata** [cedcraftscodes/portfolio#1]
I wasn't able to access the context menu because somehow the event has been `preventDefault()`ed. Suggesting to enable this since people also access Web-specific context menus for certain actions.

**Comment by ac-opensource** [comment]
Closed without action and explanation. Future employers beware.

**Comment by TheoryOfNekomata** [comment]
I could not fathom how my suggestion was turned down just like that. I demand an explanation, please. Just helping a fellow dev, no bad intentions whatsoever :(

**Comment by cedcraftscodes** [comment]
Disabling the context menu was intentional. Thanks!

**Comment by TheoryOfNekomata** [comment]
Then you could have said it beforehand, instead of closing my issues without any explanation :) . That kind of behavior is _detrimental_ to the community. Should you have to reject any suggestions, at least make your actions sensible. No offense meant, buddy. Just helping peers. Cheers :)
